# Generated by Django 5.1 on 2024-11-19 04:25

import django.db.models.deletion
import gestion_hotel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Huesped', models.CharField(default=gestion_hotel.models.generate_guest_id, editable=False, max_length=10, unique=True)),
                ('RUN', models.CharField(max_length=10)),
                ('Nombres', models.CharField(max_length=20)),
                ('Apellidos', models.CharField(max_length=20)),
                ('Contacto', models.CharField(max_length=30)),
                ('Cantidad_Personas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Personal', models.CharField(default=gestion_hotel.models.generate_staff_id, editable=False, max_length=10, unique=True)),
                ('RUN', models.CharField(max_length=10)),
                ('Nombres', models.CharField(max_length=20)),
                ('Apellidos', models.CharField(max_length=20)),
                ('Contacto', models.CharField(max_length=30)),
                ('Rol', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('ID_Habitacion', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo_Habitacion', models.CharField(choices=[('Pequeña', 'Pequeña'), ('Mediana', 'Mediana'), ('Grande', 'Grande')], max_length=10)),
                ('Capacidad', models.IntegerField()),
                ('Orientacion', models.CharField(choices=[('PISO 1', 'PISO 1'), ('PISO 2', 'PISO 2'), ('PISO 3', 'PISO 3'), ('PISO 4', 'PISO 4')], max_length=10)),
                ('Disponibilidad', models.BooleanField(default=True)),
                ('Precio', models.IntegerField()),
                ('Huesped', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='gestion_hotel.guest')),
            ],
        ),
    ]
