# Generated by Django 5.1 on 2024-11-21 04:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FECHA_PAGO', models.DateTimeField(default=django.utils.timezone.now)),
                ('Tipo_Pago', models.CharField(choices=[('debito', 'Débito'), ('credito', 'Crédito')], max_length=10)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_hotel.room')),
                ('Huesped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_hotel.guest')),
            ],
        ),
    ]
