# Generated by Django 5.1 on 2024-11-22 20:02

import gestion_hotel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_hotel', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ID_Pago',
            field=models.CharField(default=gestion_hotel.models.generar_id_pago, max_length=10, unique=True),
        ),
    ]
