# Generated by Django 5.1 on 2024-11-22 20:03

import gestion_hotel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_hotel', '0003_payment_id_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='ID_Pago',
            field=models.CharField(default=gestion_hotel.models.generar_id_pago, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
