# Generated by Django 5.1 on 2024-11-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_hotel', '0005_alter_payment_id_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='Contacto',
            field=models.EmailField(max_length=50),
        ),
    ]
